In [1]:
# kütüphaneler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#veri yükleme
veriler = pd.read_csv('veriler.csv')
type(veriler)

pandas.core.frame.DataFrame

In [3]:
#veri ön işleme
boy = veriler[['boy']]
print(boy)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166


In [4]:
# nesne yönelimli model 
class insan:
    boy = 180
    def kosmak(self,b):
        return b + 10
ali = insan()
print(ali.boy)
print(ali.kosmak(90))

180
100


In [5]:
#eksik veriler
from sklearn.impute import SimpleImputer #eksik veriler için kütüphane
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') #eksik verileri ortalamaya göre doldur
yas = veriler.iloc[:,1:4].values 
imputer = imputer.fit(yas[:,1:4]) #fit fonksiyonu ile verileri öğren
yas[:,1:4]=imputer.transform(yas[:,1:4]) #transform fonksiyonu ile verileri dönüştür
print(yas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


In [6]:
#veri tipleri

#kategorik veriler
#nominal veriler = örneğin ülke isimleri, cinsiyet gibi, sıralanamazlar
#ordinal veriler = örneğin eğitim seviyesi gibi sıralanabilirler


#sayısal veriler
#oran veriler = örneğin maaş, yaş gibi
#aralık veriler = örneğin sıcaklık gibi


In [7]:
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [8]:
#verimizde ülke ve cinsiyet kategorik verilerdir. Bu verileri sayısal verilere çevirmemiz gerekiyor.
#kolonda kim varsa ona göre 1 diğerlerine 0 değeri verir.
#bu işlem için sklearn kütüphanesinden preprocessing modülünü kullanacağız.
ulke = veriler.iloc[:,0:1].values #ilk : tüm satırları al, 0:1 ilk kolonu al
from sklearn import preprocessing #sklearn kütüphanesinden preprocessing modülünü al
le = preprocessing.LabelEncoder() #LabelEncoder nesnesi oluştur
ulke[:,0] = le.fit_transform(veriler.iloc[:,0]) #fit_transform ile verileri dönüştür :,0 = tüm satırları al, 0. kolonu al
ohe = preprocessing.OneHotEncoder() #OneHotEncoder nesnesi oluştur
ulke = ohe.fit_transform(ulke).toarray() #fit_transform ile verileri dönüştür
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [9]:
# verilerin birleştirilmesi ve dataframe oluşturulması
sonuc = pd.DataFrame(data=ulke, index=range(22), columns=['fr','tr','us']) #data=ulke = veriler, index=range(22) = satır sayısı, columns=['fr','tr','us'] = kolon isimleri
sonuc2=pd.DataFrame(data=yas, index=range(22),columns=["boy","kilo","yas"])
cinsiyet = veriler.iloc[:,-1].values #son kolonu al
sonuc3=pd.DataFrame(data=cinsiyet,index=range(22),columns=['cinsiyet'])
#dataframe birleştirme işlemi
s=pd.concat([sonuc,sonuc2],axis=1) #axis=1 kolon bazlı birleştirme yani yatay birleştirme
s2=pd.concat([s,sonuc3],axis=1) #axis=1 kolon bazlı birleştirme yani yatay birleştirme
print(s2)

     fr   tr   us  boy  kilo  yas cinsiyet
0   0.0  1.0  0.0  130    30   10        e
1   0.0  1.0  0.0  125    36   11        e
2   0.0  1.0  0.0  135    34   10        k
3   0.0  1.0  0.0  133    30    9        k
4   0.0  1.0  0.0  129    38   12        e
5   0.0  1.0  0.0  180    90   30        e
6   0.0  1.0  0.0  190    80   25        e
7   0.0  1.0  0.0  175    90   35        e
8   0.0  1.0  0.0  177    60   22        k
9   0.0  0.0  1.0  185   105   33        e
10  0.0  0.0  1.0  165    55   27        k
11  0.0  0.0  1.0  155    50   44        k
12  0.0  0.0  1.0  160    58   39        k
13  0.0  0.0  1.0  162    59   41        k
14  0.0  0.0  1.0  167    62   55        k
15  1.0  0.0  0.0  174    70   47        e
16  1.0  0.0  0.0  193    90   23        e
17  1.0  0.0  0.0  187    80   27        e
18  1.0  0.0  0.0  183    88   28        e
19  1.0  0.0  0.0  159    40   29        k
20  1.0  0.0  0.0  164    66   32        k
21  1.0  0.0  0.0  166    56   42        k


In [10]:
# verilerin eğitim ve test için bölünmesi
from sklearn.model_selection import train_test_split #train_test_split kütüphanesinden train_test_split modülünü al
x_train,x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0) #test_size=0.33 = test verisi %33, random_state=0 = verileri karıştır
#x=bağımsız değişkenler = s yani sonuc, sonuc2 
#y=bağımlı değişkenler= sonuc3 yani cinsiyet


In [11]:
from sklearn.preprocessing import StandardScaler #StandardScaler kütüphanesinden StandardScaler modülünü al
# boy kilo yas kolonlarını standartlaştır
# standartlaştırma = x-ort/standart sapma
# bu işlem verileri birbirine yaklaştırır çünkü verilerin birbirine yakın olması daha iyi sonuç verir
sc=StandardScaler()
x_train=sc.fit_transform(x_train) #fit_transform ile verileri dönüştür
x_test=sc.fit_transform(x_test) #fit_transform ile verileri dönüştür
print(x_train)
print(x_test)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.26680787]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.        ]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178 -0.17787191]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.15616745]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.33403936]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.44467979]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.17787191]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.71148766]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.88935957]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.26680787]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.42297532]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.33403936]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  1.95659106]
 [-0.63245553 -1.15470054