In [2]:
#kukla değişken 
"""
açıklama:
kukla değişken ne demektir?
kukla değişkenler, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi için kullanılır.
kukla değişkenlerin kullanılmasının sebebi, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi gerekliliğidir.
kukla değişkenlerin kullanılmasının sebebi, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi gerekliliğidir.
kukla değişkenlerin kullanılmasının sebebi, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi gerekliliğidir.
"""

'\naçıklama:\nkukla değişken ne demektir?\nkukla değişkenler, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi için kullanılır.\nkukla değişkenlerin kullanılmasının sebebi, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi gerekliliğidir.\nkukla değişkenlerin kullanılmasının sebebi, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi gerekliliğidir.\nkukla değişkenlerin kullanılmasının sebebi, kategorik değişkenlerin sayısal değişkenlere dönüştürülmesi gerekliliğidir.\n'

In [3]:
'''
p value:
p value değeri ne demektir?
p value değeri, hipotez testlerinde kullanılan bir değerdir.
p değeri genellikle 0.05 olarak kabul edilir.
p değeri 0.05'ten küçükse, H0 hipotezi reddedilir.
p değeri 0.05'ten büyükse, H1 hipotezi reddedilir.
h0 hipotezi : iki değişken arasında anlamlı bir ilişki yoktur.
h1 hipotezi : iki değişken arasında anlamlı bir ilişki vardır.
'''

"\np value:\np value değeri ne demektir?\np value değeri, hipotez testlerinde kullanılan bir değerdir.\np değeri genellikle 0.05 olarak kabul edilir.\np değeri 0.05'ten küçükse, H0 hipotezi reddedilir.\np değeri 0.05'ten büyükse, H1 hipotezi reddedilir.\nh0 hipotezi : iki değişken arasında anlamlı bir ilişki yoktur.\nh1 hipotezi : iki değişken arasında anlamlı bir ilişki vardır.\n"

In [4]:
#veri hazırlama
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
veriler =pd.read_csv('veriler3.csv')

In [6]:
#encoder: Kategorik -> Numeric
ulke = veriler.iloc[:,0:1].values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ulke[:,0] = le.fit_transform(ulke[:,0]) #:,0 ilk kolonu al demek
print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [11]:
#onehotencoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]]


In [8]:
# numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data = ulke, index = range(22), columns=['fr','tr','us'])
print(sonuc)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [13]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
yas = veriler.iloc[:,1:4].values
print(yas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


In [16]:
sonuc2=pd.DataFrame(data=yas, index=range(22),columns=["boy","kilo","yas"])
print(sonuc2)

    boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42


In [25]:
#cinsiyet verilerini numerik hale getirme
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cinsiyet = veriler.iloc[:,-1:].values

cinsiyet[:,0] = le.fit_transform(cinsiyet[:,0])
print(cinsiyet)


[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [26]:
sonuc3 = pd.DataFrame(data = cinsiyet, index = range(22), columns=['cinsiyet'])
print(sonuc3)

   cinsiyet
0         0
1         0
2         1
3         1
4         0
5         0
6         0
7         0
8         1
9         0
10        1
11        1
12        1
13        1
14        1
15        0
16        0
17        0
18        0
19        1
20        1
21        1


In [27]:
s=pd.concat([sonuc,sonuc2],axis=1)
print(s)

     fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42


In [28]:
s1=pd.concat([s,sonuc3],axis=1)
print(s1)

     fr   tr   us  boy  kilo  yas cinsiyet
0   0.0  1.0  0.0  130    30   10        0
1   0.0  1.0  0.0  125    36   11        0
2   0.0  1.0  0.0  135    34   10        1
3   0.0  1.0  0.0  133    30    9        1
4   0.0  1.0  0.0  129    38   12        0
5   0.0  1.0  0.0  180    90   30        0
6   0.0  1.0  0.0  190    80   25        0
7   0.0  1.0  0.0  175    90   35        0
8   0.0  1.0  0.0  177    60   22        1
9   0.0  0.0  1.0  185   105   33        0
10  0.0  0.0  1.0  165    55   27        1
11  0.0  0.0  1.0  155    50   44        1
12  0.0  0.0  1.0  160    58   39        1
13  0.0  0.0  1.0  162    59   41        1
14  0.0  0.0  1.0  167    62   55        1
15  1.0  0.0  0.0  174    70   47        0
16  1.0  0.0  0.0  193    90   23        0
17  1.0  0.0  0.0  187    80   27        0
18  1.0  0.0  0.0  183    88   28        0
19  1.0  0.0  0.0  159    40   29        1
20  1.0  0.0  0.0  164    66   32        1
21  1.0  0.0  0.0  166    56   42        1


In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [35]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


LinearRegression()

In [45]:
y_pred = regressor.predict(x_test)
print(y_pred)

[[0.01279796]
 [1.12036863]
 [0.94990297]
 [0.92862582]
 [0.27526065]
 [0.35384956]
 [1.03567453]
 [0.67387829]]


In [47]:
boy=s1.iloc[:,3:4].values
print(boy)

[[130]
 [125]
 [135]
 [133]
 [129]
 [180]
 [190]
 [175]
 [177]
 [185]
 [165]
 [155]
 [160]
 [162]
 [167]
 [174]
 [193]
 [187]
 [183]
 [159]
 [164]
 [166]]


In [48]:
sol=s1.iloc[:,:3]
sag=s1.iloc[:,4:]

In [49]:
print(sol)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [50]:
print(sag)

    kilo  yas cinsiyet
0     30   10        0
1     36   11        0
2     34   10        1
3     30    9        1
4     38   12        0
5     90   30        0
6     80   25        0
7     90   35        0
8     60   22        1
9    105   33        0
10    55   27        1
11    50   44        1
12    58   39        1
13    59   41        1
14    62   55        1
15    70   47        0
16    90   23        0
17    80   27        0
18    88   28        0
19    40   29        1
20    66   32        1
21    56   42        1


In [53]:
veri = pd.concat([sol,sag],axis=1)
print(veri)
# boy kolonu kalmadı

     fr   tr   us  kilo  yas cinsiyet
0   0.0  1.0  0.0    30   10        0
1   0.0  1.0  0.0    36   11        0
2   0.0  1.0  0.0    34   10        1
3   0.0  1.0  0.0    30    9        1
4   0.0  1.0  0.0    38   12        0
5   0.0  1.0  0.0    90   30        0
6   0.0  1.0  0.0    80   25        0
7   0.0  1.0  0.0    90   35        0
8   0.0  1.0  0.0    60   22        1
9   0.0  0.0  1.0   105   33        0
10  0.0  0.0  1.0    55   27        1
11  0.0  0.0  1.0    50   44        1
12  0.0  0.0  1.0    58   39        1
13  0.0  0.0  1.0    59   41        1
14  0.0  0.0  1.0    62   55        1
15  1.0  0.0  0.0    70   47        0
16  1.0  0.0  0.0    90   23        0
17  1.0  0.0  0.0    80   27        0
18  1.0  0.0  0.0    88   28        0
19  1.0  0.0  0.0    40   29        1
20  1.0  0.0  0.0    66   32        1
21  1.0  0.0  0.0    56   42        1


In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(veri,boy,test_size=0.33,random_state=0)


In [58]:
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1.fit(x_train,y_train)


LinearRegression()

In [62]:
y_pred = regressor1.predict(x_test)
print(y_pred)
print(y_test)

[[182.26638686]
 [152.87161474]
 [162.79386375]
 [158.30668577]
 [130.82888952]
 [173.96138408]
 [150.12782663]
 [157.26898922]]
[[164]
 [165]
 [167]
 [162]
 [125]
 [166]
 [155]
 [159]]


In [68]:
# geri eleme yani modelin başarısını ölçme
import statsmodels.api as sm 
# sabit değer eklemek için
X = np.append(arr=np.ones((22,1)).astype(int),values=veri,axis=1)
print(X) # sabit değer eklendi bu lineer regresyon için gerekli



[[1 0.0 1.0 0.0 30 10 0]
 [1 0.0 1.0 0.0 36 11 0]
 [1 0.0 1.0 0.0 34 10 1]
 [1 0.0 1.0 0.0 30 9 1]
 [1 0.0 1.0 0.0 38 12 0]
 [1 0.0 1.0 0.0 90 30 0]
 [1 0.0 1.0 0.0 80 25 0]
 [1 0.0 1.0 0.0 90 35 0]
 [1 0.0 1.0 0.0 60 22 1]
 [1 0.0 0.0 1.0 105 33 0]
 [1 0.0 0.0 1.0 55 27 1]
 [1 0.0 0.0 1.0 50 44 1]
 [1 0.0 0.0 1.0 58 39 1]
 [1 0.0 0.0 1.0 59 41 1]
 [1 0.0 0.0 1.0 62 55 1]
 [1 1.0 0.0 0.0 70 47 0]
 [1 1.0 0.0 0.0 90 23 0]
 [1 1.0 0.0 0.0 80 27 0]
 [1 1.0 0.0 0.0 88 28 0]
 [1 1.0 0.0 0.0 40 29 1]
 [1 1.0 0.0 0.0 66 32 1]
 [1 1.0 0.0 0.0 56 42 1]]


In [72]:
# dizi oluşturmak için
X_l= veri.iloc[:,[0,1,2,3,4,5]].values
X_l=np.array(X_l,dtype=float)

In [74]:
model =sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Thu, 30 Nov 2023   Prob (F-statistic):           5.41e-07
Time:                        22:47:55   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           103.4708      9.878     10.475      0.0

In [ ]:
"""Bu çıktı, bir OLS (Ordinary Least Squares) regresyon modelinin sonuçlarını gösteren istatistiksel bilgileri içerir. OLS, regresyon analizinde yaygın olarak kullanılan bir yöntemdir ve amacı, bağımsız değişkenlerin (x1, x2, ..., x6) bağımlı değişken üzerindeki etkilerini belirlemektir.

İşte bu çıktıdaki önemli kısımlar:

Dep. Variable (Bağımlı Değişken): 'y', bağımlı değişkenin adını temsil eder.

R-squared (R Kare): R-kare, modelin bağımlı değişkenin varyansını ne kadar iyi açıkladığını ölçen bir istatistik değeridir. Bu durumda, R-kare değeri 0.885, yani modelin bağımlı değişkenin %88.5'ini açıkladığı anlamına gelir.

Adj. R-squared (Düzeltilmiş R Kare): Bu, R-kare'nin bir düzeltilmiş versiyonudur ve bağımsız değişken sayısını dikkate alır. Düzeltilmiş R-kare, modelin karmaşıklığına göre düzeltilmiş bir R-kare değeridir.

F-statistic: F-istatistiği, modelin genel uyumunun istatistiksel olarak anlamlı olup olmadığını belirten bir değerdir.

Prob (F-statistic): F-istatistiğinin p-değeri, F-istatistiğinin istatistiksel anlamlılığını değerlendiren bir ölçüdür. 5.41e-07 değeri çok küçük olduğu için, bu modelin genel olarak anlamlı olduğunu gösterir.

Coefficients (Katsayılar): x1'den x6'ya kadar olan bağımsız değişkenlerin katsayıları ve bunların istatistiksel anlamlılıkları bu bölümde bulunmaktadır.

t-values ve P>|t|: Her bir katsayının t-değeri ve buna karşılık gelen p-değeri. P>|t| değeri, bir katsayının istatistiksel olarak anlamlı olup olmadığını gösterir. Küçük p-değerleri (genellikle 0.05'ten küçük) istatistiksel olarak anlamlı katsayıları gösterir.

Omnibus, Prob(Omnibus), Jarque-Bera (JB), Prob(JB): Normal dağılımı test etmek için kullanılan istatistiksel test sonuçları.

Durbin-Watson: Otokorelasyonun varlığını kontrol etmek için kullanılan bir istatistik değeri. 2.759 değeri, otokorelasyon olasılığını değerlendirir.

Cond. No. (Condition Number): Çoklu doğrusallık durumunu kontrol etmek için kullanılan bir değer. Düşük bir değer, çoklu doğrusallık olasılığını gösterir.

Bu çıktı, regresyon modelinin performansını ve istatistiksel özelliklerini değerlendirmek için kullanılır. Modellerin doğruluğunu, anlamlılığını ve güvenilirliğini değerlendirmek için bu tür istatistiklere dikkat etmek önemlidir."""